# Generated by Django 5.1.1 on 2024-09-23 17:26

from django.db import migrations, models
from django_pg_eventstream.operations import CreateEventStreamTriggers


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        CreateEventStreamTriggers(
            model_name="Product",
            table_name="product_product",
            tracked_fields=["quantity"],
            pk_field="id",
        ),
    ]
